### ISSUE TITLE
Suggest enabling user to select output directory

### ISSUE THREAD

**Issue by shamavir** [healthonrails/annolid#1]
Presently, main.py -v /path/to/video ... deposits all of the extracted frames into the annolid/extracted_frames directory.  Suggest another argument that would enable user to deposit the frames into an arbitrary directory with the same name as the video file.  

So, given the existence of a video file video444.mkv, the command:

python annolid/main.py -v /home/me/video444.mkv --extract_frames=100 --to /home/me

would create the directory /home/me/video444 and put all 100 extracted frames into it.  I've assumed for present purposes that the argument flag is --to, but of course that could be whatever.

**Comment by healthonrails** [comment]
Implemented the requested feature
