### ISSUE TITLE
Tracking Animals

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#10]
if you don't mind to tell me what files do I put in when this window appears (besides the video, the ".pth" file and the output directory):
![image](https://user-images.githubusercontent.com/47870128/123324077-b1086600-d536-11eb-986e-de91a2f03d28.png)

**Comment by healthonrails** [comment]
This user interface dialog is designed inference YOLACT models on your local GPU workstation. 
The config file option data.yaml file in the COCO dataset folder.

**Comment by Hatem-Jr** [comment]
I did that and this error happened: 
![Screenshot (16)](https://user-images.githubusercontent.com/47870128/123327999-53c2e380-d53b-11eb-96e8-46357f690894.png)
