### ISSUE TITLE
Training the Model

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#12]
Hello, I wanted to know if there's any way to continue training my model if the Detectron google collab "disconnected/busy"

**Comment by Hatem-Jr** [comment]
I also tried to run it on the local pc and got this message but I think it could be fixable: 
![Screenshot (18)](https://user-images.githubusercontent.com/47870128/123425336-4ef54280-d5c2-11eb-9343-11d3fb7d46b7.png)

**Comment by Hatem-Jr** [comment]
this error appears in this line in the collab:
![Screenshot (19)](https://user-images.githubusercontent.com/47870128/123427492-fbd0bf00-d5c4-11eb-9371-2a3731f16966.png)

**Comment by healthonrails** [comment]
You need to keep the page open and check it frequently. 
Or you can buy Colab pro for the machine to stay on longer.

**Comment by Hatem-Jr** [comment]
ctrl+shift+i --->console paste this: 
function KeepClicking(){

   console.log(“Clicking”);

   document.querySelector(“colab-toolbar-button#connect”).click()

}setInterval(KeepClicking,60000) stimulates a click every 60 seconds
