### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#14]
Hi previously you had a command in the installation part that had something to do with requirements.txt (I had to uninstall anaconda for reasons) and I took this command:

git clone --recurse-submodules https://github.com/healthonrails/annolid.git
cd annolid 
pip install -e .

but this error appears:
Requirement already satisfied: numpy>=1.18.2 in c:\users\owner\appdata\local\programs\python\python39\lib\site-packages (from annolid==1.0.1) (1.19.5)
Requirement already satisfied: scipy>=1.5.2 in c:\users\owner\appdata\local\programs\python\python39\lib\site-packages (from annolid==1.0.1) (1.6.2)
Requirement already satisfied: easydict>=1.9 in c:\users\owner\appdata\local\programs\python\python39\lib\site-packages (from annolid==1.0.1) (1.9)
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from annolid) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.14.53, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.2.54)
ERROR: No matching distribution found for opencv-python==4.1.2.30

and I remember last time I did the installation there was something related to the requirements.txt file

**Comment by healthonrails** [comment]
It seems that you are using python 3.9. You can try to install 4.3.0.38 version or you might need to switch back to Python 3.7.
