### ISSUE TITLE
Running Colab code on local machine

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#17]
Hi, I am trying to take the google colab cells and run it on a local machine where there are other experiment analysis (Morris Water) that uses opencv techniques and link it up with my GUI tkinter (part of my thesis application), I'm asking here if that's possible to do ?

**Comment by healthonrails** [comment]
Yes, it is possible. Please share and contribute your code if you are able to do it successfully. 
Good luck!
