### ISSUE TITLE
environment.yml file should have specific package version

### ISSUE THREAD

**Issue by jeremyforest** [healthonrails/annolid#23]
Need to specify the package version of all the required package. Will avoid annolid package breaking unintentionally.

**Comment by healthonrails** [comment]
Thanks for creating the environment.yml file. Should we close this issue?

**Comment by jeremyforest** [comment]
I don't think I did. This file was already there. I just think we should have the exact package version in there so as to make the conda virtual environment reproducible and can monitor if any update in the dependencies break annolid.

**Comment by healthonrails** [comment]
Solved
