### ISSUE TITLE
Error uploading local dataset file 

### ISSUE THREAD

**Issue by jeremyforest** [healthonrails/annolid#30]
Running the cells:
```
from google.colab import files
uploaded = files.upload()
dataset =  list(uploaded.keys())[0]  #"/content/dataset.zip"

```
leads to an error in Firefox. 
This seems like a common error. See [https://github.com/googlecolab/colabtools/issues/51](https://github.com/googlecolab/colabtools/issues/51). 
Solution : add a comment to use chrome in the documentation

**Comment by jeremyforest** [comment]
@healthonrails  Can I close this ?

**Comment by healthonrails** [comment]
> 

Sure. Please go ahead!
