### ISSUE TITLE
Make 2 different environments

### ISSUE THREAD

**Issue by jeremyforest** [healthonrails/annolid#39]
The environment for annolid dev and using annolid don't necessarily need the same packages (for example there is no need for the jupyterbook dependencies when using annolid and not doing dev). Should have 2 different environments to simplifying the user environment.

**Comment by healthonrails** [comment]
Choose one of the following environment files based on your machine's configuration:
If you have a GPU-enabled machine, use the environment.yml file.
If you do not have a GPU-enabled machine, use the environment_no_GPU.yml file.
If you plan to develop Annolid, use the environment_dev.yml file.

Create a Conda environment based on the specifications in the chosen environment file using the following command:
```bash
conda env create -f environment_file.yml
```
Replace environment_file.yml with the name of the environment file you chose. This command will create a new Conda environment with the required packages and dependencies needed to run Annolid on your machine.
