### ISSUE TITLE
labelme2coco.py fails silently; update documentation

### ISSUE THREAD

**Issue by shamavir** [healthonrails/annolid#4]
Labelme's labelme2coco.py script fails silently if the --labels file does not exist.  We could push a fix to labelme, or just add a warning to our documentation.  (This screenshot shows a success, but if I change the filename from labels.txt to, say, labelme.txt, it fails).  

![Annolid error 02, 17 Sept 2020, no response when labels-txt file does not exist](https://user-images.githubusercontent.com/5396347/93555479-11350080-f944-11ea-93d5-6aa2cd5cda97.jpg)

**Comment by healthonrails** [comment]
Solved by launching from annolid GUI COCO format button
