### ISSUE TITLE
debug docker container

### ISSUE THREAD

**Issue by jeremyforest** [healthonrails/annolid#40]
error when building

> Sending build context to Docker daemon  4.096kB
> Step 1/27 : FROM nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
>  ---> 8adcfd968b3c
> Step 2/27 : LABEL maintainer "Chen Yang <healthonrails@gmail.com>"
>  ---> Using cache
>  ---> 7e7e02a9459c
> Step 3/27 : ENV DEBIAN_FRONTEND=noninteractive
>  ---> Using cache
>  ---> 7c5ca1e9df14
> Step 4/27 : RUN   apt-get update -qq &&   apt-get install -qq -y     git     wget     ca-certificates     python3     python3-pip     python3-matplotlib     python3-pyqt5     python3-opencv     python3-dev     sudo     ninja-build    ffmpeg     && rm -rf /var/lib/apt/lists/*
>  ---> Using cache
>  ---> a22c20e197ab
> Step 5/27 : RUN python3 -m pip install -U pip setuptools wheel
>  ---> Using cache
>  ---> f7e9d7b5ff39
> Step 6/27 : RUN ln -sv /usr/bin/python3 /usr/bin/python
>  ---> Using cache
>  ---> e87f52895675
> Step 7/27 : ARG USER_ID=1000
>  ---> Using cache
>  ---> 9344a5135837
> Step 8/27 : RUN useradd -m --no-log-init --system  --uid ${USER_ID} annoliduser -g sudo
>  ---> Using cache
>  ---> 11f40a02841d
> Step 9/27 : RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
>  ---> Using cache
>  ---> 9eb2e6c2dc06
> Step 10/27 : USER annoliduser
>  ---> Using cache
>  ---> df7d71ab0c9e
> Step 11/27 : WORKDIR /home/annoliduser
>  ---> Using cache
>  ---> a5c61d65fb5a
> Step 12/27 : ENV PATH="/home/annoliduser/.local/bin:${PATH}"
>  ---> Using cache
>  ---> 202101906d44
> Step 13/27 : RUN wget https://bootstrap.pypa.io/get-pip.py && 	python3 get-pip.py --user && 	rm get-pip.py
>  ---> Using cache
>  ---> e789f0a6c9ee
> Step 14/27 : RUN pip install --user tensorboard cmake
>  ---> Using cache
>  ---> 1f0c78e8ea73
> Step 15/27 : RUN pip install --user torch==1.9 torchvision==0.10 -f https://download.pytorch.org/whl/cu111/torch_stable.html
>  ---> Using cache
>  ---> a86d6719ca43
> Step 16/27 : RUN pip install --user 'git+https://github.com/facebookresearch/fvcore'
>  ---> Using cache
>  ---> fe52f81762a4
> Step 17/27 : RUN git clone https://github.com/facebookresearch/detectron2 detectron2_repo
>  ---> Using cache
>  ---> dfa0248e4926
> Step 18/27 : ENV FORCE_CUDA="1"
>  ---> Using cache
>  ---> 593512e107de
> Step 19/27 : ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
>  ---> Using cache
>  ---> b34f627a0759
> Step 20/27 : ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"
>  ---> Using cache
>  ---> fbe7e4a32db6
> Step 21/27 : RUN pip install --user -e detectron2_repo
>  ---> Using cache
>  ---> dbb9a35c1ff1
> Step 22/27 : RUN git clone --recurse-submodules https://github.com/healthonrails/annolid.git
>  ---> Using cache
>  ---> a71d6683ab10
> Step 23/27 : RUN pip install --user -e annolid
>  ---> Running in 8a76d6fe57d4
> Obtaining file:///home/annoliduser/annolid
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Collecting numpy>=1.18.2
>   Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
> Collecting scipy>=1.5.2
>   Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
> Collecting easydict>=1.9
>   Downloading easydict-1.9.tar.gz (6.4 kB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Collecting opencv-python==4.1.2.30
>   Downloading opencv_python-4.1.2.30-cp36-cp36m-manylinux1_x86_64.whl (28.3 MB)
> Collecting opencv-contrib-python==4.1.2.30
>   Downloading opencv_contrib_python-4.1.2.30-cp36-cp36m-manylinux1_x86_64.whl (34.3 MB)
> Collecting opencv-python-headless==4.1.2.30
>   Downloading opencv_python_headless-4.1.2.30-cp36-cp36m-manylinux1_x86_64.whl (21.8 MB)
> Requirement already satisfied: PyYAML>=5.3 in ./.local/lib/python3.6/site-packages (from annolid==1.0.1) (6.0)
> Collecting labelme>=4.5.6
>   Downloading labelme-4.6.0.tar.gz (1.5 MB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Collecting decord>=0.4.0
>   Downloading decord-0.6.0-py3-none-manylinux2010_x86_64.whl (13.6 MB)
> Requirement already satisfied: torch>=1.4.0 in ./.local/lib/python3.6/site-packages (from annolid==1.0.1) (1.9.0+cu111)
> Requirement already satisfied: torchvision>=0.5.0 in ./.local/lib/python3.6/site-packages (from annolid==1.0.1) (0.10.0+cu111)
> Collecting pandas>=1.1.3
>   Downloading pandas-1.1.5-cp36-cp36m-manylinux1_x86_64.whl (9.5 MB)
> Requirement already satisfied: pycocotools>=2.0.2 in ./.local/lib/python3.6/site-packages (from annolid==1.0.1) (2.0.2)
> Requirement already satisfied: tensorboard>=2.3.0 in ./.local/lib/python3.6/site-packages (from annolid==1.0.1) (2.7.0)
> Collecting imageio>=2.8.0
>   Downloading imageio-2.14.1-py3-none-any.whl (3.3 MB)
> Collecting imageio-ffmpeg>=0.4.2
>   Downloading imageio_ffmpeg-0.4.5-py3-none-manylinux2010_x86_64.whl (26.9 MB)
> Collecting PyQtWebEngine>=5.15.1
>   Downloading PyQtWebEngine-5.15.5-cp36-abi3-manylinux1_x86_64.whl (228 kB)
> ERROR: Could not find a version that satisfies the requirement simplification>=0.5.12 (from annolid) (from versions: 0.2.1, 0.2.2, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.3.2, 0.3.3, 0.3.7, 0.3.8, 0.3.9, 0.4.2, 0.4.4, 0.5.1, 0.5.2, 0.5.7)
> ERROR: No matching distribution found for simplification>=0.5.12
> The command '/bin/sh -c pip install --user -e annolid' returned a non-zero code: 1
>

**Comment by healthonrails** [comment]
How about trying to change simplification>=0.5.12 to  simplification>=0.5.7?

**Comment by jeremyforest** [comment]
Just a problem with my local environment. working fine building it in new environment. Sorry about that.
