### ISSUE TITLE
jupyterbook not building all pages properly

### ISSUE THREAD

**Issue by jeremyforest** [healthonrails/annolid#43]
Jupyterbook building seems to have some issues to debug as some pages are not rendered/updated in the final version. Not sure why at the moment. Need to look into it. 
E.g. the tutorials are not updated
E.g.2 some pages appear only when going through the previous ones but not when landing on the main page.

**Comment by healthonrails** [comment]
I updated the documentation as follows. 
`pip install ghp-import
cd annolid/book
ghp-import -n -p -f _build/html`
Please let me know if the problems still exist. 
Thanks!

**Comment by healthonrails** [comment]
I rebuild the book and now some of the missing tutorials were updated e.g. http://annolid.com/tutorials/Annolid_on_Detectron2_Tutorial_3_Evaluate_our_model.html.

**Comment by jeremyforest** [comment]
ah cool thanks @healthonrails  ! Was it just a matter of rebuilding then ?

**Comment by jeremyforest** [comment]
Something's still off though. When I arrive at [annolid.com](annolid.com) I don't see all the pages on the left part of the page but once I click on 'Introduction', all the missing ones appear. Any idea what could be wrong still ? I haven't taken the time to look at it in details yet.

**Comment by healthonrails** [comment]
> 

I haven't figured out this issue. I am not sure why only `Tutorials` section not loading in the first place.

**Comment by shamavir** [comment]
I think I've got it.   The problem recurs when I click on the picture atop the sidebar, which loads https://annolid.com/README.html.  It does not recur when I click on the text "Annolid Documentation" in the sidebar, which loads https://annolid.com/content/README.html.  So you seem to have two README.html files in play, and the former loads a deprecated sidebar.

**Comment by shamavir** [comment]
Actually, the link under "Annolid Documentation" text seems to be relative, probably just coded as "README.html", because it loads the deprecated sidebar when I start from annolid.com, but loads the correct sidebar after I am already in the /content subdirectory because of having clicked on some other link in the sidebar previously.

**Comment by shamavir** [comment]
Also loads a deprecated main README.html file.  And for what it's worth, I don't think we should market the tracking video under the Examples as "pose estimation."  It isn't really that.

**Comment by healthonrails** [comment]
> Also loads a deprecated main README.html file. And for what it's worth, I don't think we should market the tracking video under the Examples as "pose estimation." It isn't really that.

Wow! Great! This is exactly the issue. I have fixed it. I also changed the "pose estimation" to "keypoint detection based on body parts segmentation".

**Comment by jeremyforest** [comment]
Nice catch @shamavir ! Thanks for the fix @healthonrails :+1:  Closing this thread.
