### ISSUE TITLE
Error when trying to open annolid

### ISSUE THREAD

**Issue by syr6** [healthonrails/annolid#44]
Traceback (most recent call last):
 File “/Applications/Applications/anaconda3/bin/annolid”, line 6, in <module>
  from pkg_resources import load_entry_point
 File “/Applications/Applications/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 3242, in <module>
  @_call_aside
 File “/Applications/Applications/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 3226, in _call_aside
  f(*args, **kwargs)
 File “/Applications/Applications/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 3255, in _initialize_master_working_set
  working_set = WorkingSet._build_master()
 File “/Applications/Applications/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 568, in _build_master
  ws.require(__requires__)
 File “/Applications/Applications/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 886, in require
  needed = self.resolve(parse_requirements(requirements))
 File “/Applications/Applications/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py”, line 772, in resolve
  raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The ‘dataclasses>=0.6’ distribution was not found and is required by annolid

**Comment by healthonrails** [comment]
Python3.6 is end-of-life. `dataclasses` is included in python 3.7. So Here are the commands to create a new conda python 3.7 env and install the annolid. 
`conda create -n annolid python=3.7`
`conda activate annolid`
`cd annolid`
`pip install -e .`
