### ISSUE TITLE
Crash when open quality control 

### ISSUE THREAD

**Issue by healthonrails** [healthonrails/annolid#48]
Right now we are trying to do quality control, but when I start the process on my MacBook Pro laptop, python quits unexpectedly, and I was wondering if you had any advice (I have attached several screenshots that may contain more information about the specific error).
ValueError: Buffer has the wrong number of dimensions expected 2 got 1

**Comment by jeremyforest** [comment]
@healthonrails  Will try out as soon as I can. Can't see the screenshots though is that normal ?

**Comment by healthonrails** [comment]
> @healthonrails Will try out as soon as I can. Can't see the screenshots though is that normal ?

<img width="640" alt="thumbnail_Screen Shot_2 AM" src="https://user-images.githubusercontent.com/1077233/202543364-bddf7a0a-9986-45a4-9814-cf5880c45d5a.png">

<img width="640" alt="thumbnail_Screen Shot AM" src="https://user-images.githubusercontent.com/1077233/202543392-4eb
<img width="569" alt="thumbnail_Screen ShotAM" src="https://user-images.githubusercontent.com/1077233/202543434-60ba983c-a276-4ee5-9610-86fdff3053cd.png">
<img width="640" alt="thumbnail_Screen Shot 4AM" src="https://user-images.githubusercontent.com/1077233/202543436-4faff5e2-b675-486e-8cc9-f67a76ce74ff.png">
<img width="640" alt="thumbnail_Screen Shot 3 AM" src="https://user-images.githubusercontent.com/1077233/202543440-2c1d52a1-7020-4c60-9c88-4077591deb38.png">
6889f-1229-4b55-a75c-895d061de683.png">

**Comment by healthonrails** [comment]
The memory leak was caused by the simplification/cutil.pyx code. 
Switched to using the NumPy array for the input contours fixed the issue.
