### ISSUE TITLE
HQ-SAM integration

### ISSUE THREAD

**Issue by walywalid24** [healthonrails/annolid#52]
Quick tutorial to how to add/use HQ-SAM (or different versions of SAM with ViT-H finely tuned encoder) for annotation purposes.
Thank you for the contributions.

**Comment by healthonrails** [comment]
Please check this Colab notebook https://colab.research.google.com/drive/1QwAbn5hsdqKOD5niuBzuqQX4eLCbNKFL?usp=sharing.

**Comment by healthonrails** [comment]
Please check the video here https://youtu.be/bCCobNAwWvM?si=GrSgMwVhYJbWbB5H for details.
