### ISSUE TITLE
Where to get the datasets ?

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#6]
Hi I installed your program and after a couple of installations it finally recognized that I AM using the GPU XD then I selected the track animal option chose the video, the weights, the config file, and output directory but the output directory had no output and this is what the console had to say:
![Screenshot (8)](https://user-images.githubusercontent.com/47870128/122906184-2b2bc580-d352-11eb-9385-f9609ebafacf.png)
So if you can help me or give me any link to datasets OR even uploading the dataset and it's configuration file you showcase in the tutorial videos (specially the Novel Object Test ones) that would be a great help because I'm sort of new to this stuff and only worked with object tracking through a yolov4 google collab notebook. Those are the files I used https://drive.google.com/drive/folders/1Y-9lG4IXMby8Ffj9lS5dm6R2R9v3u_a8?usp=sharing backup folder has the .weights file and the .cfg is the configuration

**Comment by healthonrails** [comment]
The current UI for **Track animals** dialog only supports a trained YOLACT model. 
If you like, you can try the command line for the YOLOv5 models. 
```
cd annold
python main.py -v /path/to/my_video.mp4 --track=YOLOV5 --weights=detector/yolov5/runs/exp5_yolov5x_my_model/weights/best.pt
```
However, I noticed that you have a YOLOV4 model which is not supported.  We have no plans to support YOLOV4:). 
Here is the example dataset https://drive.google.com/file/d/1fUXCLnoJ5SwXg54mj0NBKGzidsV8ALVR/view?usp=sharing. 
FYI: You can check the Colab notebook https://github.com/healthonrails/annolid/blob/master/docs/tutorials/Annolid_of_Detectron2_Tutorial.ipynb for how to train a model it and use it for inference. 

> Hi I installed your program and after a couple of installations it finally recognized that I AM using the GPU XD then I selected the track animal option chose the video, the weights, the config file, and output directory but the output directory had no output and this is what the console had to say:
> ![Screenshot (8)](https://user-images.githubusercontent.com/47870128/122906184-2b2bc580-d352-11eb-9385-f9609ebafacf.png)
> So if you can help me or give me any link to datasets OR even uploading the dataset and it's configuration file you showcase in the tutorial videos (specially the Novel Object Test ones) that would be a great help because I'm sort of new to this stuff and only worked with object tracking through a yolov4 google collab notebook. Those are the files I used https://drive.google.com/drive/folders/1Y-9lG4IXMby8Ffj9lS5dm6R2R9v3u_a8?usp=sharing backup folder has the .weights file and the .cfg is the configuration
