### ISSUE TITLE
Error in training the model

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#7]
Hi it's me again XD, I'm having an issue where I used the dataset in the github repo and changed the file locations in the data.yaml file to match the dataset file and picture locations but here's what's in the data.yaml file that I use as a config file for training (these paths are copied from the file explorer and the backslash is changed to match the format): 

DATASET:
    name: 'novelctrlk6_8'
    train_info: 'D:/custom code/Weights/Github Dataset/novelctrlk6_8_coco_dataset/train/annotations.json'
    train_images: 'D:/custom code/Weights/Github Dataset/novelctrlk6_8_coco_dataset/train/JPEGImages'
    valid_info: 'D:/custom code/Weights/Github Dataset/novelctrlk6_8_coco_dataset/valid/annotations.json'
    valid_images: 'D:/custom code/Weights/Github Dataset/novelctrlk6_8_coco_dataset/valid/JPEGImages'
    class_names: ['nose', 'left_ear', 'right_ear', 'tail_base', 'mouse', 'centroid']
YOLACT:
    name: 'novelctrlk6_8'
    dataset: 'dataset_novelctrlk6_8_coco'
    max_size: 512
  
and here's the output error in the console:
![Screenshot (11)](https://user-images.githubusercontent.com/47870128/123074029-40b6f300-d417-11eb-8f70-bc67f4559eb5.png)

Plus I re-installed annolid again according to the annolid installation document this time:
https://healthonrails.github.io/annolid/guide.html#video-guide
so as not to put that error on the installation because this time there was no installation error and this was the final message:
![Screenshot (12)](https://user-images.githubusercontent.com/47870128/123074855-fa15c880-d417-11eb-8646-c66337652939.png)

I know I'm asking too much but if there could be a way on how to train or if I'm even using the correct files whether I'm training or using visualization or even tracking animals because I feel a part of it is that I'm using the wrong files to begin with

Thanks :D
ps:- can you take down those 2 videos because I might get in trouble with my uni: https://www.youtube.com/watch?v=1Ua7Mpsi1yM&t=13s 
https://www.youtube.com/watch?v=3ScyTbTa7fc

I sent them to you on a google drive and was expecting if you were gonna send anything to send them on a drive as well Sorry :)

**Comment by healthonrails** [comment]
If you want to train YOLACT on your own computer, you need to install Pytorch 1.4.0 and torchvision==0.5.0. 
Please check the details from here https://colab.research.google.com/github/healthonrails/annolid/blob/master/docs/tutorials/Train_networks_tutorial_v1.0.1.ipynb and  https://github.com/healthonrails/yolact. 

I have deleted the videos based on your video.

**Comment by Hatem-Jr** [comment]
I did what you said now is that normal ?
![Screenshot (13)](https://user-images.githubusercontent.com/47870128/123133474-0d448a80-d450-11eb-81c4-b6dd6e18b7c7.png)

**Comment by healthonrails** [comment]
You might need to check your CUDA versions. 
# CUDA 10.1
pip install torch==1.4.0 torchvision==0.5.0

# CUDA 9.2
pip install torch==1.4.0+cu92 torchvision==0.5.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html
For more info, please check here https://pytorch.org/get-started/previous-versions/.
