### ISSUE TITLE
A Trained Model

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#8]
Look this is more of a request than an issue can you upload a trained model that has the following labels? :
mouse
vole
body
body_centroid
left_ear
right_ear
nose
head
hand
arm
wall
base_of_tail
rearing
object_investigation
object
centroid

so that I can use it for any novel object test please ? because finding bugs in things like installation can be such a drag so if this is faster than that it would really help. 

Also if you don't mind to tell me what files do I put in when this window appears (besides the video and the output directory):
![Screenshot 2021-06-23 190924](https://user-images.githubusercontent.com/47870128/123139583-ab3b5380-d456-11eb-8843-9d90653706fb.png)

Thanks :D

**Comment by healthonrails** [comment]
Our trained model on different animals and environment settings might not work for your video. 
You can use the example Google Colab(https://github.com/healthonrails/annolid/blob/master/docs/tutorials/Annolid_of_Detectron2_Tutorial.ipynb) or (https://github.com/healthonrails/annolid/blob/master/docs/tutorials/Train_networks_tutorial_v1.0.1.ipynb) to train your own models in a few hours without needing to install anything on your computer.

**Comment by Hatem-Jr** [comment]
I'm short on time but in one of my deleted videos you had a mask-cnn detection on my video which was pre trained in your case can you upload it on a google drive if you still have it ?

**Comment by healthonrails** [comment]
Sorry I deleted them as you requested. I trained and predicted it in the example Detectron2 Google Colab for about two hours. Hope you can easily reproduce it.

**Comment by Hatem-Jr** [comment]
ok so I trained the model for like 51 minutes and at that time stamp the collab notebook disconnected because of the internet how do I continue training from the iteration I stopped at? (it stopped at iteration 999)

Thanks :)

**Comment by Hatem-Jr** [comment]
Also I tried to track animal from the GUI on the model_0000999.pth file but there was a problem in the metric.json file that said "End of file expected.json" next to line 2 curly bracket

**Comment by Hatem-Jr** [comment]
if you don't mind to tell me what files do I put in when this window appears (besides the video and the output directory):
Screenshot 2021-06-23 190924
