### ISSUE TITLE
How to label "actions" in extracted frames

### ISSUE THREAD

**Issue by Hatem-Jr** [healthonrails/annolid#9]
I get the idea that we can put points on certain parts of the mouse and draw a polygon around it and label it as mouse, however I cannot get or not able to visualize the idea of labelling certain actions like: "rearing", "object investigation" or even "grooming" (although I'll only use "object investigation"),  I don't quite get how to label the action itself because if done incorrectly it could result in the whole tracking video being "object investigation"

Thanks for the detectron link :D

**Comment by healthonrails** [comment]
You can name the polygon "rearing", "object investigation", or "grooming" instead of "mouse". 
Then the network will classify each mask into these actions.

**Comment by Hatem-Jr** [comment]
Good Idea thanks :D
